### ISSUE TITLE
Support for AWS key[name]/value format

### ISSUE THREAD

**Issue by n8felton** [bjarneo/dotenvjson#3]
If you're interested in an additional challenge, [passing `environment` in a AWS ECS task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html) uses a different format than most JSON. 

AWS actually does this in a lot of places, but this is my most recent annoyance with it.

```
    "environment": [
      {
        "name": "string",
        "value": "string"
      }
    ]
```
The goal would be to take something like

```
HOST=db.host
USER=root
PASSWORD=betterlucknexttime!
```
and output it like (or similar)
```
{
  "name": "HOST",
  "value": "db.host"
},
{
  "name": "USER",
  "value": "root"
},
{
  "name": "PASSWORD",
  "value": "betterlucknexttime!"
},
```

**Comment by bjarneo** [comment]
That is actually a great idea. Not sure when I got spare time to fix it, but shouldn't be that much work.

**Comment by bjarneo** [comment]
@n8felton thank you for the great suggestion, this is now a new addition to this cli; https://github.com/bjarneo/dotenvjson/releases/tag/v1.3.0

Have a nice summer!
