### ISSUE TITLE
Empty Environment vars will panic

### ISSUE THREAD

**Issue by smurfy** [bjarneo/dotenvjson#5]
If for example i have:

````
FOO=
BAR=lala
````

Tested with .env file and using `env | dotenvjson` as source

It will crash with something like this:

![image](https://github.com/bjarneo/dotenvjson/assets/805790/24484abb-17dc-44c5-8b05-cbb3a0a79f95)

**Comment by bjarneo** [comment]
Thank you for your issue. That is really not good. Will look into this!

**Comment by bjarneo** [comment]
https://github.com/bjarneo/dotenvjson/releases/tag/v1.3.1

**Comment by bjarneo** [comment]
So, the current go binary builder is broken, so for the latest just clone the repo and run
`go build -o bin/dotenvjson`

**Comment by bjarneo** [comment]
https://github.com/bjarneo/dotenvjson/releases

**Comment by bjarneo** [comment]
https://github.com/bjarneo/dotenvjson/releases/tag/v1.3.2
